server:
  servlet:
    context-path: /
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    include-binding-errors: never

spring:
  profiles:
    include:
      - core
      - service
#    active: local
    active: dev

springdoc:
  packages-to-scan: kr.co.opennote.booster
  swagger-ui:
    tags-sorter: alpha
    path: /api-docs

--- # local
spring:
  config:
    activate:
      on-profile: local

server:
  domain: http://localhost:8080

api:
  version: /api/v1

--- # dev
spring:
  config:
    activate:
      on-profile: dev

server:
  domain: http://121.179.119.221:58080

api:
  version: /api/v1
